[settings]
npm.bun = true

[tasks]
dev = { run = "bun run tauri dev", description = "Run the development server" }

[tools]
bun = "latest"
node = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:shadcn" = "latest"
