#!/usr/bin/env bash

#MISE description="Install dependencies for Tauri presentation app on Ubuntu"

sudo apt update
sudo apt install libwebkit2gtk-4.1-dev \
  build-essential \
  curl \
  wget \
  file \
  libxdo-dev \
  libssl-dev \
  libayatana-appindicator3-dev \
  librsvg2-dev
